// Generated by BUCKLESCRIPT VERSION 3.1.4, PLEASE EDIT WITH CARE
'use strict';


function fetchPost(url, body) {
  fetch(url, {
        method: "POST",
        body: body
      });
  return /* () */0;
}

function fetchGet(url, cb) {
  fetch(url).then((function (prim) {
            return prim.json();
          })).then(cb);
  return /* () */0;
}

exports.fetchPost = fetchPost;
exports.fetchGet = fetchGet;
/* No side effect */
